swagger: "2.0.0"
info:
  description: "This is the practice API doct for BookBox"
  version: "1.0.0"
  title: "Swagger BookBox"
  contact:
    email: "emma140626@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/api/v1"
tags:
- name: "books"
  description: "Everything about Books"
schemes:
- "https"
- "http"
paths:
  /books:
    get:
      tags:
      - "books"
      summary: "Get all book information"
      description: "Return all pet information"
      operationId: "getAllBooks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/books"
        "404":
          description: "not found data"
          schema:
            $ref: "#/definitions/error"
        "409":
          description: "conflict"
          schema:
            $ref: "#/definitions/error"
        "500":
          description: "operating error"
          schema:
            $ref: "#/definitions/error"
definitions:
  books:
    type: "object"
    properties:
      status:
        type: "string"
        description: "indicate the data status"
      data:
        type: "array"
        $ref: "#/definitions/book"
  book:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      authorid:
        type: "integer"
        format: "int64"
      publisher:
        type: "string"
      published:
        type: "string"
        format: "date-time"
      category:
        type: "string"
      isbn:
        type: "string"
      language:
        type: "string"
        description: "written language"
      imageurl:
        type: "string"
      description:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
  error:
    type: "object"
    properties:
      status:
        type: "string"
      message:
        type: "string"
        description: "error message"
